version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app
    environment:
      - DB_URL=postgres://ryorfece:9ieUIoobWYO7kKnSOMgwfTo3Y8BDoDwO@lallah.db.elephantsql.com/ryorfece
      - JWT_SECRET=(!*890)jGN1
      - JWT_EXPIRE=3600
    stdin_open: true
    tty: true
volumes:
  db:
networks:
  app:
    driver: bridge