# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: "CI (dev)"

on:
  push:
    branches:
      - dev

jobs:
  setup:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Setup Nodejs and npm
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm i
      
    - name: Build dependency
      run: npm build
      
    - name: Start project
      run: npm start
  lint:
    name: Run linters
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: [14.x]
          cache: npm
      - run: npm install
      - run: npm lint
  test:
    name: Run unit tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: [14.x]
          cache: npm
      - run: npm install
      - run: npm test

